name: Build and Push release image
on:
  push:
    branches:
      - testReleasev1.0.0

env:
  ECR_REPOSITORY: app-assets-smart-contract
jobs:
  build-and-push:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push release image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build . -t $ECR_REGISTRY/$ECR_REPOSITORY:v1.0.0
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:v1.0.0"
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:v1.0.0
